#ifndef __ATLSCILEXER_H__
#define __ATLSCILEXER_H__

#pragma once

#ifndef __cplusplus
	#error ATL requires C++ compilation (use a .cpp suffix)
#endif

#ifndef __ATLAPP_H__
	#error atlscilexer.h requires atlapp.h to be included first
#endif

#ifndef __ATLWIN_H__
	#error atlscilexer.h requires atlwin.h to be included first
#endif

#ifndef SCINTILLA_H
#include <scintilla.h>
#endif

namespace WTL
{

template<class TBase>
class CSciLexerCtrlT : public TBase
{
public:
	SciFnDirect m_DirectFunction;
	LRESULT m_DirectPointer;

// Constructors
	CSciLexerCtrlT(HWND hWnd = NULL) : TBase(hWnd)
	{
		m_DirectFunction = 0;
		m_DirectPointer = 0;
	}

	CSciLexerCtrlT< TBase >& operator =(HWND hWnd)
	{
		m_hWnd = hWnd;
		m_DirectFunction = 0;
		m_DirectPointer = 0;
		return *this;
	}

	HWND Create(HWND hWndParent, ATL::_U_RECT rect = NULL, LPCTSTR szWindowName = NULL,
			DWORD dwStyle = 0, DWORD dwExStyle = 0,
			ATL::_U_MENUorID MenuOrID = 0U, LPVOID lpCreateParam = NULL)
	{
		return TBase::Create(GetWndClassName(), hWndParent, rect.m_lpRect, szWindowName, dwStyle, dwExStyle, MenuOrID.m_hMenu, lpCreateParam);
	}

	void EnableDirectFunction(bool enable)
	{
		ATLASSERT(::IsWindow(m_hWnd));;
		if (enable)
		{
			m_DirectFunction = (SciFnDirect)::SendMessage(m_hWnd, SCI_GETDIRECTFUNCTION, 0, 0);
			m_DirectPointer = ::SendMessage(m_hWnd, SCI_GETDIRECTPOINTER, 0, 0);
		}
		else
		{
			m_DirectFunction = 0;
			m_DirectPointer = 0;
		}
	}

	LRESULT Call(UINT Msg, WPARAM wParam = 0, LPARAM lParam = 0) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));;
		if (m_DirectFunction)
			return m_DirectFunction(m_DirectPointer, Msg, wParam, lParam);
		else
			return ::SendMessage(m_hWnd, Msg, wParam, lParam);
	}

// Attributes
	static LPCTSTR GetWndClassName()
	{
		return _T("Scintilla");
	}

/* ++Autogenerated -- start of section automatically generated from Scintilla.iface */
	void AddText(int length, LPCSTR text) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_ADDTEXT, (WPARAM) length, (LPARAM) text);
	}

	void AddStyledText(int length, char * c) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_ADDSTYLEDTEXT, (WPARAM) length, (LPARAM) c);
	}

	void InsertText(int pos, LPCSTR text) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_INSERTTEXT, (WPARAM) pos, (LPARAM) text);
	}

	void ChangeInsertion(int length, LPCSTR text) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_CHANGEINSERTION, (WPARAM) length, (LPARAM) text);
	}

	void ClearAll() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_CLEARALL, 0, 0);
	}

	void DeleteRange(int pos, int deleteLength) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_DELETERANGE, (WPARAM) pos, (LPARAM) deleteLength);
	}

	void ClearDocumentStyle() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_CLEARDOCUMENTSTYLE, 0, 0);
	}

	int GetLength() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETLENGTH, 0, 0);
	}

	int GetCharAt(int pos) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETCHARAT, (WPARAM) pos, 0);
	}

	int GetCurrentPos() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETCURRENTPOS, 0, 0);
	}

	int GetAnchor() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETANCHOR, 0, 0);
	}

	int GetStyleAt(int pos) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETSTYLEAT, (WPARAM) pos, 0);
	}

	void Redo() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_REDO, 0, 0);
	}

	void SetUndoCollection(bool collectUndo) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETUNDOCOLLECTION, (WPARAM) collectUndo, 0);
	}

	void SelectAll() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SELECTALL, 0, 0);
	}

	void SetSavePoint() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETSAVEPOINT, 0, 0);
	}

	int GetStyledText(Sci_TextRange * tr) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETSTYLEDTEXT, 0, (LPARAM) tr);
	}

	bool CanRedo() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_CANREDO, 0, 0);
	}

	int MarkerLineFromHandle(int handle) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_MARKERLINEFROMHANDLE, (WPARAM) handle, 0);
	}

	void MarkerDeleteHandle(int handle) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_MARKERDELETEHANDLE, (WPARAM) handle, 0);
	}

	bool GetUndoCollection() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETUNDOCOLLECTION, 0, 0);
	}

	int GetViewWS() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETVIEWWS, 0, 0);
	}

	void SetViewWS(int viewWS) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETVIEWWS, (WPARAM) viewWS, 0);
	}

	int PositionFromPoint(int x, int y) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_POSITIONFROMPOINT, (WPARAM) x, (LPARAM) y);
	}

	int PositionFromPointClose(int x, int y) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_POSITIONFROMPOINTCLOSE, (WPARAM) x, (LPARAM) y);
	}

	void GotoLine(int line) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_GOTOLINE, (WPARAM) line, 0);
	}

	void GotoPos(int pos) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_GOTOPOS, (WPARAM) pos, 0);
	}

	void SetAnchor(int posAnchor) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETANCHOR, (WPARAM) posAnchor, 0);
	}

	int GetCurLine(int length, LPSTR text) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETCURLINE, (WPARAM) length, (LPARAM) text);
	}

	int GetCurLine(CSimpleStringA& strText)
	{
		int nLength;
		LPSTR pszText;

		nLength = GetCurLineLength();
		pszText = strText.GetBuffer(nLength+1);
		nLength = GetCurLine(nLength+1, pszText);
		strText.ReleaseBuffer();

		return nLength;
	}

	int GetCurLineLength(int length) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETCURLINE, (WPARAM) length, 0)
	}

	int GetEndStyled() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETENDSTYLED, 0, 0);
	}

	void ConvertEOLs(int eolMode) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_CONVERTEOLS, (WPARAM) eolMode, 0);
	}

	int GetEOLMode() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETEOLMODE, 0, 0);
	}

	void SetEOLMode(int eolMode) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETEOLMODE, (WPARAM) eolMode, 0);
	}

	void StartStyling(int pos, int mask) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_STARTSTYLING, (WPARAM) pos, (LPARAM) mask);
	}

	void SetStyling(int length, int style) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETSTYLING, (WPARAM) length, (LPARAM) style);
	}

	bool GetBufferedDraw() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETBUFFEREDDRAW, 0, 0);
	}

	void SetBufferedDraw(bool buffered) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETBUFFEREDDRAW, (WPARAM) buffered, 0);
	}

	void SetTabWidth(int tabWidth) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETTABWIDTH, (WPARAM) tabWidth, 0);
	}

	int GetTabWidth() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETTABWIDTH, 0, 0);
	}

	void SetCodePage(int codePage) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETCODEPAGE, (WPARAM) codePage, 0);
	}

	void MarkerDefine(int markerNumber, int markerSymbol) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_MARKERDEFINE, (WPARAM) markerNumber, (LPARAM) markerSymbol);
	}

	void MarkerSetFore(int markerNumber, COLORREF fore) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_MARKERSETFORE, (WPARAM) markerNumber, (LPARAM) fore);
	}

	void MarkerSetBack(int markerNumber, COLORREF back) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_MARKERSETBACK, (WPARAM) markerNumber, (LPARAM) back);
	}

	void MarkerSetBackSelected(int markerNumber, COLORREF back) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_MARKERSETBACKSELECTED, (WPARAM) markerNumber, (LPARAM) back);
	}

	void MarkerEnableHighlight(bool enabled) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_MARKERENABLEHIGHLIGHT, (WPARAM) enabled, 0);
	}

	int MarkerAdd(int line, int markerNumber) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_MARKERADD, (WPARAM) line, (LPARAM) markerNumber);
	}

	void MarkerDelete(int line, int markerNumber) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_MARKERDELETE, (WPARAM) line, (LPARAM) markerNumber);
	}

	void MarkerDeleteAll(int markerNumber) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_MARKERDELETEALL, (WPARAM) markerNumber, 0);
	}

	int MarkerGet(int line) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_MARKERGET, (WPARAM) line, 0);
	}

	int MarkerNext(int lineStart, int markerMask) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_MARKERNEXT, (WPARAM) lineStart, (LPARAM) markerMask);
	}

	int MarkerPrevious(int lineStart, int markerMask) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_MARKERPREVIOUS, (WPARAM) lineStart, (LPARAM) markerMask);
	}

	void MarkerDefinePixmap(int markerNumber, LPCSTR pixmap) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_MARKERDEFINEPIXMAP, (WPARAM) markerNumber, (LPARAM) pixmap);
	}

	void MarkerAddSet(int line, int set) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_MARKERADDSET, (WPARAM) line, (LPARAM) set);
	}

	void MarkerSetAlpha(int markerNumber, int alpha) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_MARKERSETALPHA, (WPARAM) markerNumber, (LPARAM) alpha);
	}

	void SetMarginTypeN(int margin, int marginType) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETMARGINTYPEN, (WPARAM) margin, (LPARAM) marginType);
	}

	int GetMarginTypeN(int margin) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETMARGINTYPEN, (WPARAM) margin, 0);
	}

	void SetMarginWidthN(int margin, int pixelWidth) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETMARGINWIDTHN, (WPARAM) margin, (LPARAM) pixelWidth);
	}

	int GetMarginWidthN(int margin) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETMARGINWIDTHN, (WPARAM) margin, 0);
	}

	void SetMarginMaskN(int margin, int mask) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETMARGINMASKN, (WPARAM) margin, (LPARAM) mask);
	}

	int GetMarginMaskN(int margin) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETMARGINMASKN, (WPARAM) margin, 0);
	}

	void SetMarginSensitiveN(int margin, bool sensitive) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETMARGINSENSITIVEN, (WPARAM) margin, (LPARAM) sensitive);
	}

	bool GetMarginSensitiveN(int margin) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETMARGINSENSITIVEN, (WPARAM) margin, 0);
	}

	void SetMarginCursorN(int margin, int cursor) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETMARGINCURSORN, (WPARAM) margin, (LPARAM) cursor);
	}

	int GetMarginCursorN(int margin) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETMARGINCURSORN, (WPARAM) margin, 0);
	}

	void StyleClearAll() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_STYLECLEARALL, 0, 0);
	}

	void StyleSetFore(int style, COLORREF fore) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_STYLESETFORE, (WPARAM) style, (LPARAM) fore);
	}

	void StyleSetBack(int style, COLORREF back) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_STYLESETBACK, (WPARAM) style, (LPARAM) back);
	}

	void StyleSetBold(int style, bool bold) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_STYLESETBOLD, (WPARAM) style, (LPARAM) bold);
	}

	void StyleSetItalic(int style, bool italic) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_STYLESETITALIC, (WPARAM) style, (LPARAM) italic);
	}

	void StyleSetSize(int style, int sizePoints) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_STYLESETSIZE, (WPARAM) style, (LPARAM) sizePoints);
	}

	void StyleSetFont(int style, LPCSTR fontName) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_STYLESETFONT, (WPARAM) style, (LPARAM) fontName);
	}

	void StyleSetEOLFilled(int style, bool filled) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_STYLESETEOLFILLED, (WPARAM) style, (LPARAM) filled);
	}

	void StyleResetDefault() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_STYLERESETDEFAULT, 0, 0);
	}

	void StyleSetUnderline(int style, bool underline) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_STYLESETUNDERLINE, (WPARAM) style, (LPARAM) underline);
	}

	COLORREF StyleGetFore(int style) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_STYLEGETFORE, (WPARAM) style, 0);
	}

	COLORREF StyleGetBack(int style) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_STYLEGETBACK, (WPARAM) style, 0);
	}

	bool StyleGetBold(int style) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_STYLEGETBOLD, (WPARAM) style, 0);
	}

	bool StyleGetItalic(int style) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_STYLEGETITALIC, (WPARAM) style, 0);
	}

	int StyleGetSize(int style) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_STYLEGETSIZE, (WPARAM) style, 0);
	}

	int StyleGetFont(int style, LPSTR fontName) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_STYLEGETFONT, (WPARAM) style, (LPARAM) fontName);
	}

	int StyleGetFont(int style, CSimpleStringA& strText) const
	{
		int nLength;
		LPSTR pszText;

		nLength = StyleGetFontLength(style);
		pszText = strText.GetBuffer(nLength+1);
		nLength = StyleGetFont(style, pszText);
		strText.ReleaseBuffer();

		return nLength;
	}

	int StyleGetFontLength(int style) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_STYLEGETFONT, (WPARAM) style, 0)
	}

	bool StyleGetEOLFilled(int style) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_STYLEGETEOLFILLED, (WPARAM) style, 0);
	}

	bool StyleGetUnderline(int style) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_STYLEGETUNDERLINE, (WPARAM) style, 0);
	}

	int StyleGetCase(int style) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_STYLEGETCASE, (WPARAM) style, 0);
	}

	int StyleGetCharacterSet(int style) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_STYLEGETCHARACTERSET, (WPARAM) style, 0);
	}

	bool StyleGetVisible(int style) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_STYLEGETVISIBLE, (WPARAM) style, 0);
	}

	bool StyleGetChangeable(int style) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_STYLEGETCHANGEABLE, (WPARAM) style, 0);
	}

	bool StyleGetHotSpot(int style) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_STYLEGETHOTSPOT, (WPARAM) style, 0);
	}

	void StyleSetCase(int style, int caseForce) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_STYLESETCASE, (WPARAM) style, (LPARAM) caseForce);
	}

	void StyleSetSizeFractional(int style, int caseForce) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_STYLESETSIZEFRACTIONAL, (WPARAM) style, (LPARAM) caseForce);
	}

	int StyleGetSizeFractional(int style) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_STYLEGETSIZEFRACTIONAL, (WPARAM) style, 0);
	}

	void StyleSetWeight(int style, int weight) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_STYLESETWEIGHT, (WPARAM) style, (LPARAM) weight);
	}

	int StyleGetWeight(int style) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_STYLEGETWEIGHT, (WPARAM) style, 0);
	}

	void StyleSetCharacterSet(int style, int characterSet) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_STYLESETCHARACTERSET, (WPARAM) style, (LPARAM) characterSet);
	}

	void StyleSetHotSpot(int style, bool hotspot) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_STYLESETHOTSPOT, (WPARAM) style, (LPARAM) hotspot);
	}

	void SetSelFore(bool useSetting, COLORREF fore) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETSELFORE, (WPARAM) useSetting, (LPARAM) fore);
	}

	void SetSelBack(bool useSetting, COLORREF back) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETSELBACK, (WPARAM) useSetting, (LPARAM) back);
	}

	int GetSelAlpha() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETSELALPHA, 0, 0);
	}

	void SetSelAlpha(int alpha) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETSELALPHA, (WPARAM) alpha, 0);
	}

	bool GetSelEOLFilled() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETSELEOLFILLED, 0, 0);
	}

	void SetSelEOLFilled(bool filled) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETSELEOLFILLED, (WPARAM) filled, 0);
	}

	void SetCaretFore(COLORREF fore) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETCARETFORE, (WPARAM) fore, 0);
	}

	void AssignCmdKey(DWORD km, int msg) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_ASSIGNCMDKEY, (WPARAM) km, (LPARAM) msg);
	}

	void ClearCmdKey(DWORD km) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_CLEARCMDKEY, (WPARAM) km, 0);
	}

	void ClearAllCmdKeys() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_CLEARALLCMDKEYS, 0, 0);
	}

	void SetStylingEx(int length, LPCSTR styles) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETSTYLINGEX, (WPARAM) length, (LPARAM) styles);
	}

	void StyleSetVisible(int style, bool visible) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_STYLESETVISIBLE, (WPARAM) style, (LPARAM) visible);
	}

	int GetCaretPeriod() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETCARETPERIOD, 0, 0);
	}

	void SetCaretPeriod(int periodMilliseconds) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETCARETPERIOD, (WPARAM) periodMilliseconds, 0);
	}

	void SetWordChars(LPCSTR characters) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETWORDCHARS, 0, (LPARAM) characters);
	}

	int GetWordChars(LPSTR characters) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETWORDCHARS, 0, (LPARAM) characters);
	}

	int GetWordChars(CSimpleStringA& strText) const
	{
		int nLength;
		LPSTR pszText;

		nLength = GetWordCharsLength();
		pszText = strText.GetBuffer(nLength+1);
		nLength = GetWordChars(pszText);
		strText.ReleaseBuffer();

		return nLength;
	}

	int GetWordCharsLength() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETWORDCHARS, 0)
	}

	void BeginUndoAction() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_BEGINUNDOACTION, 0, 0);
	}

	void EndUndoAction() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_ENDUNDOACTION, 0, 0);
	}

	void IndicSetStyle(int indic, int style) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_INDICSETSTYLE, (WPARAM) indic, (LPARAM) style);
	}

	int IndicGetStyle(int indic) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_INDICGETSTYLE, (WPARAM) indic, 0);
	}

	void IndicSetFore(int indic, COLORREF fore) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_INDICSETFORE, (WPARAM) indic, (LPARAM) fore);
	}

	COLORREF IndicGetFore(int indic) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_INDICGETFORE, (WPARAM) indic, 0);
	}

	void IndicSetUnder(int indic, bool under) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_INDICSETUNDER, (WPARAM) indic, (LPARAM) under);
	}

	bool IndicGetUnder(int indic) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_INDICGETUNDER, (WPARAM) indic, 0);
	}

	void SetWhitespaceFore(bool useSetting, COLORREF fore) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETWHITESPACEFORE, (WPARAM) useSetting, (LPARAM) fore);
	}

	void SetWhitespaceBack(bool useSetting, COLORREF back) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETWHITESPACEBACK, (WPARAM) useSetting, (LPARAM) back);
	}

	void SetWhitespaceSize(int size) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETWHITESPACESIZE, (WPARAM) size, 0);
	}

	int GetWhitespaceSize() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETWHITESPACESIZE, 0, 0);
	}

	void SetStyleBits(int bits) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETSTYLEBITS, (WPARAM) bits, 0);
	}

	int GetStyleBits() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETSTYLEBITS, 0, 0);
	}

	void SetLineState(int line, int state) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETLINESTATE, (WPARAM) line, (LPARAM) state);
	}

	int GetLineState(int line) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETLINESTATE, (WPARAM) line, 0);
	}

	int GetMaxLineState() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETMAXLINESTATE, 0, 0);
	}

	bool GetCaretLineVisible() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETCARETLINEVISIBLE, 0, 0);
	}

	void SetCaretLineVisible(bool show) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETCARETLINEVISIBLE, (WPARAM) show, 0);
	}

	COLORREF GetCaretLineBack() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETCARETLINEBACK, 0, 0);
	}

	void SetCaretLineBack(COLORREF back) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETCARETLINEBACK, (WPARAM) back, 0);
	}

	void StyleSetChangeable(int style, bool changeable) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_STYLESETCHANGEABLE, (WPARAM) style, (LPARAM) changeable);
	}

	void AutoCShow(int lenEntered, LPCSTR itemList) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_AUTOCSHOW, (WPARAM) lenEntered, (LPARAM) itemList);
	}

	void AutoCCancel() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_AUTOCCANCEL, 0, 0);
	}

	bool AutoCActive() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_AUTOCACTIVE, 0, 0);
	}

	int AutoCPosStart() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_AUTOCPOSSTART, 0, 0);
	}

	void AutoCComplete() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_AUTOCCOMPLETE, 0, 0);
	}

	void AutoCStops(LPCSTR characterSet) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_AUTOCSTOPS, 0, (LPARAM) characterSet);
	}

	void AutoCSetSeparator(int separatorCharacter) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_AUTOCSETSEPARATOR, (WPARAM) separatorCharacter, 0);
	}

	int AutoCGetSeparator() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_AUTOCGETSEPARATOR, 0, 0);
	}

	void AutoCSelect(LPCSTR text) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_AUTOCSELECT, 0, (LPARAM) text);
	}

	void AutoCSetCancelAtStart(bool cancel) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_AUTOCSETCANCELATSTART, (WPARAM) cancel, 0);
	}

	bool AutoCGetCancelAtStart() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_AUTOCGETCANCELATSTART, 0, 0);
	}

	void AutoCSetFillUps(LPCSTR characterSet) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_AUTOCSETFILLUPS, 0, (LPARAM) characterSet);
	}

	void AutoCSetChooseSingle(bool chooseSingle) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_AUTOCSETCHOOSESINGLE, (WPARAM) chooseSingle, 0);
	}

	bool AutoCGetChooseSingle() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_AUTOCGETCHOOSESINGLE, 0, 0);
	}

	void AutoCSetIgnoreCase(bool ignoreCase) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_AUTOCSETIGNORECASE, (WPARAM) ignoreCase, 0);
	}

	bool AutoCGetIgnoreCase() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_AUTOCGETIGNORECASE, 0, 0);
	}

	void UserListShow(int listType, LPCSTR itemList) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_USERLISTSHOW, (WPARAM) listType, (LPARAM) itemList);
	}

	void AutoCSetAutoHide(bool autoHide) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_AUTOCSETAUTOHIDE, (WPARAM) autoHide, 0);
	}

	bool AutoCGetAutoHide() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_AUTOCGETAUTOHIDE, 0, 0);
	}

	void AutoCSetDropRestOfWord(bool dropRestOfWord) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_AUTOCSETDROPRESTOFWORD, (WPARAM) dropRestOfWord, 0);
	}

	bool AutoCGetDropRestOfWord() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_AUTOCGETDROPRESTOFWORD, 0, 0);
	}

	void RegisterImage(int type, LPCSTR xpmData) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_REGISTERIMAGE, (WPARAM) type, (LPARAM) xpmData);
	}

	void ClearRegisteredImages() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_CLEARREGISTEREDIMAGES, 0, 0);
	}

	int AutoCGetTypeSeparator() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_AUTOCGETTYPESEPARATOR, 0, 0);
	}

	void AutoCSetTypeSeparator(int separatorCharacter) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_AUTOCSETTYPESEPARATOR, (WPARAM) separatorCharacter, 0);
	}

	void AutoCSetMaxWidth(int characterCount) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_AUTOCSETMAXWIDTH, (WPARAM) characterCount, 0);
	}

	int AutoCGetMaxWidth() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_AUTOCGETMAXWIDTH, 0, 0);
	}

	void AutoCSetMaxHeight(int rowCount) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_AUTOCSETMAXHEIGHT, (WPARAM) rowCount, 0);
	}

	int AutoCGetMaxHeight() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_AUTOCGETMAXHEIGHT, 0, 0);
	}

	void SetIndent(int indentSize) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETINDENT, (WPARAM) indentSize, 0);
	}

	int GetIndent() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETINDENT, 0, 0);
	}

	void SetUseTabs(bool useTabs) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETUSETABS, (WPARAM) useTabs, 0);
	}

	bool GetUseTabs() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETUSETABS, 0, 0);
	}

	void SetLineIndentation(int line, int indentSize) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETLINEINDENTATION, (WPARAM) line, (LPARAM) indentSize);
	}

	int GetLineIndentation(int line) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETLINEINDENTATION, (WPARAM) line, 0);
	}

	int GetLineIndentPosition(int line) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETLINEINDENTPOSITION, (WPARAM) line, 0);
	}

	int GetColumn(int pos) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETCOLUMN, (WPARAM) pos, 0);
	}

	int CountCharacters(int startPos, int endPos) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_COUNTCHARACTERS, (WPARAM) startPos, (LPARAM) endPos);
	}

	void SetHScrollBar(bool show) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETHSCROLLBAR, (WPARAM) show, 0);
	}

	bool GetHScrollBar() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETHSCROLLBAR, 0, 0);
	}

	void SetIndentationGuides(int indentView) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETINDENTATIONGUIDES, (WPARAM) indentView, 0);
	}

	int GetIndentationGuides() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETINDENTATIONGUIDES, 0, 0);
	}

	void SetHighlightGuide(int column) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETHIGHLIGHTGUIDE, (WPARAM) column, 0);
	}

	int GetHighlightGuide() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETHIGHLIGHTGUIDE, 0, 0);
	}

	int GetLineEndPosition(int line) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETLINEENDPOSITION, (WPARAM) line, 0);
	}

	int GetCodePage() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETCODEPAGE, 0, 0);
	}

	COLORREF GetCaretFore() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETCARETFORE, 0, 0);
	}

	bool GetReadOnly() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETREADONLY, 0, 0);
	}

	void SetCurrentPos(int pos) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETCURRENTPOS, (WPARAM) pos, 0);
	}

	void SetSelectionStart(int pos) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETSELECTIONSTART, (WPARAM) pos, 0);
	}

	int GetSelectionStart() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETSELECTIONSTART, 0, 0);
	}

	void SetSelectionEnd(int pos) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETSELECTIONEND, (WPARAM) pos, 0);
	}

	int GetSelectionEnd() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETSELECTIONEND, 0, 0);
	}

	void SetEmptySelection(int pos) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETEMPTYSELECTION, (WPARAM) pos, 0);
	}

	void SetPrintMagnification(int magnification) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETPRINTMAGNIFICATION, (WPARAM) magnification, 0);
	}

	int GetPrintMagnification() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETPRINTMAGNIFICATION, 0, 0);
	}

	void SetPrintColourMode(int mode) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETPRINTCOLOURMODE, (WPARAM) mode, 0);
	}

	int GetPrintColourMode() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETPRINTCOLOURMODE, 0, 0);
	}

	int FindText(int flags, Sci_TextToFind * ft) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_FINDTEXT, (WPARAM) flags, (LPARAM) ft);
	}

	int FormatRange(bool draw, Sci_RangeToFormat * fr) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_FORMATRANGE, (WPARAM) draw, (LPARAM) fr);
	}

	int GetFirstVisibleLine() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETFIRSTVISIBLELINE, 0, 0);
	}

	int GetLine(int line, LPSTR text) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETLINE, (WPARAM) line, (LPARAM) text);
	}

	int GetLine(int line, CSimpleStringA& strText) const
	{
		int nLength;
		LPSTR pszText;

		nLength = GetLineLength(line);
		pszText = strText.GetBuffer(nLength+1);
		nLength = GetLine(line, pszText);
		strText.ReleaseBuffer();

		return nLength;
	}

	int GetLineLength(int line) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETLINE, (WPARAM) line, 0)
	}

	int GetLineCount() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETLINECOUNT, 0, 0);
	}

	void SetMarginLeft(int pixelWidth) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETMARGINLEFT, 0, (LPARAM) pixelWidth);
	}

	int GetMarginLeft() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETMARGINLEFT, 0, 0);
	}

	void SetMarginRight(int pixelWidth) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETMARGINRIGHT, 0, (LPARAM) pixelWidth);
	}

	int GetMarginRight() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETMARGINRIGHT, 0, 0);
	}

	bool GetModify() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETMODIFY, 0, 0);
	}

	void SetSel(int start, int end) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETSEL, (WPARAM) start, (LPARAM) end);
	}

	int GetSelText(LPSTR text) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETSELTEXT, 0, (LPARAM) text);
	}

	int GetSelText(CSimpleStringA& strText) const
	{
		int nLength;
		LPSTR pszText;

		nLength = GetSelTextLength();
		pszText = strText.GetBuffer(nLength+1);
		nLength = GetSelText(pszText);
		strText.ReleaseBuffer();

		return nLength;
	}

	int GetSelTextLength() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETSELTEXT, 0)
	}

	int GetTextRange(Sci_TextRange * tr) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETTEXTRANGE, 0, (LPARAM) tr);
	}

	void HideSelection(bool normal) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_HIDESELECTION, (WPARAM) normal, 0);
	}

	int PointXFromPosition(int pos) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_POINTXFROMPOSITION, 0, (LPARAM) pos);
	}

	int PointYFromPosition(int pos) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_POINTYFROMPOSITION, 0, (LPARAM) pos);
	}

	int LineFromPosition(int pos) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_LINEFROMPOSITION, (WPARAM) pos, 0);
	}

	int PositionFromLine(int line) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_POSITIONFROMLINE, (WPARAM) line, 0);
	}

	void LineScroll(int columns, int lines) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_LINESCROLL, (WPARAM) columns, (LPARAM) lines);
	}

	void ScrollCaret() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SCROLLCARET, 0, 0);
	}

	void ScrollRange(int secondary, int primary) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SCROLLRANGE, (WPARAM) secondary, (LPARAM) primary);
	}

	void ReplaceSel(LPCSTR text) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_REPLACESEL, 0, (LPARAM) text);
	}

	void SetReadOnly(bool readOnly) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETREADONLY, (WPARAM) readOnly, 0);
	}

	void Null() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_NULL, 0, 0);
	}

	bool CanPaste() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_CANPASTE, 0, 0);
	}

	bool CanUndo() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_CANUNDO, 0, 0);
	}

	void EmptyUndoBuffer() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_EMPTYUNDOBUFFER, 0, 0);
	}

	void Undo() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_UNDO, 0, 0);
	}

	void Cut() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_CUT, 0, 0);
	}

	void Copy() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_COPY, 0, 0);
	}

	void Paste() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_PASTE, 0, 0);
	}

	void Clear() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_CLEAR, 0, 0);
	}

	void SetText(LPCSTR text) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETTEXT, 0, (LPARAM) text);
	}

	int GetText(int length, LPSTR text) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETTEXT, (WPARAM) length, (LPARAM) text);
	}

	int GetText(CSimpleStringA& strText)
	{
		int nLength;
		LPSTR pszText;

		nLength = GetTextLength();
		pszText = strText.GetBuffer(nLength+1);
		nLength = GetText(nLength+1, pszText);
		strText.ReleaseBuffer();

		return nLength;
	}

	int GetTextLength(int length) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETTEXT, (WPARAM) length, 0)
	}

	int GetTextLength() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETTEXTLENGTH, 0, 0);
	}

	int GetDirectFunction() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETDIRECTFUNCTION, 0, 0);
	}

	int GetDirectPointer() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETDIRECTPOINTER, 0, 0);
	}

	void SetOvertype(bool overtype) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETOVERTYPE, (WPARAM) overtype, 0);
	}

	bool GetOvertype() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETOVERTYPE, 0, 0);
	}

	void SetCaretWidth(int pixelWidth) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETCARETWIDTH, (WPARAM) pixelWidth, 0);
	}

	int GetCaretWidth() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETCARETWIDTH, 0, 0);
	}

	void SetTargetStart(int pos) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETTARGETSTART, (WPARAM) pos, 0);
	}

	int GetTargetStart() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETTARGETSTART, 0, 0);
	}

	void SetTargetEnd(int pos) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETTARGETEND, (WPARAM) pos, 0);
	}

	int GetTargetEnd() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETTARGETEND, 0, 0);
	}

	int ReplaceTarget(int length, LPCSTR text) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_REPLACETARGET, (WPARAM) length, (LPARAM) text);
	}

	int ReplaceTargetRE(int length, LPCSTR text) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_REPLACETARGETRE, (WPARAM) length, (LPARAM) text);
	}

	int SearchInTarget(int length, LPCSTR text) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_SEARCHINTARGET, (WPARAM) length, (LPARAM) text);
	}

	void SetSearchFlags(int flags) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETSEARCHFLAGS, (WPARAM) flags, 0);
	}

	int GetSearchFlags() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETSEARCHFLAGS, 0, 0);
	}

	void CallTipShow(int pos, LPCSTR definition) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_CALLTIPSHOW, (WPARAM) pos, (LPARAM) definition);
	}

	void CallTipCancel() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_CALLTIPCANCEL, 0, 0);
	}

	bool CallTipActive() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_CALLTIPACTIVE, 0, 0);
	}

	int CallTipPosStart() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_CALLTIPPOSSTART, 0, 0);
	}

	void CallTipSetPosStart(int posStart) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_CALLTIPSETPOSSTART, (WPARAM) posStart, 0);
	}

	void CallTipSetHlt(int start, int end) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_CALLTIPSETHLT, (WPARAM) start, (LPARAM) end);
	}

	void CallTipSetBack(COLORREF back) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_CALLTIPSETBACK, (WPARAM) back, 0);
	}

	void CallTipSetFore(COLORREF fore) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_CALLTIPSETFORE, (WPARAM) fore, 0);
	}

	void CallTipSetForeHlt(COLORREF fore) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_CALLTIPSETFOREHLT, (WPARAM) fore, 0);
	}

	void CallTipUseStyle(int tabSize) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_CALLTIPUSESTYLE, (WPARAM) tabSize, 0);
	}

	void CallTipSetPosition(bool above) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_CALLTIPSETPOSITION, (WPARAM) above, 0);
	}

	int VisibleFromDocLine(int line) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_VISIBLEFROMDOCLINE, (WPARAM) line, 0);
	}

	int DocLineFromVisible(int lineDisplay) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_DOCLINEFROMVISIBLE, (WPARAM) lineDisplay, 0);
	}

	int WrapCount(int line) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_WRAPCOUNT, (WPARAM) line, 0);
	}

	void SetFoldLevel(int line, int level) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETFOLDLEVEL, (WPARAM) line, (LPARAM) level);
	}

	int GetFoldLevel(int line) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETFOLDLEVEL, (WPARAM) line, 0);
	}

	int GetLastChild(int line, int level) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETLASTCHILD, (WPARAM) line, (LPARAM) level);
	}

	int GetFoldParent(int line) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETFOLDPARENT, (WPARAM) line, 0);
	}

	void ShowLines(int lineStart, int lineEnd) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SHOWLINES, (WPARAM) lineStart, (LPARAM) lineEnd);
	}

	void HideLines(int lineStart, int lineEnd) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_HIDELINES, (WPARAM) lineStart, (LPARAM) lineEnd);
	}

	bool GetLineVisible(int line) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETLINEVISIBLE, (WPARAM) line, 0);
	}

	bool GetAllLinesVisible() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETALLLINESVISIBLE, 0, 0);
	}

	void SetFoldExpanded(int line, bool expanded) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETFOLDEXPANDED, (WPARAM) line, (LPARAM) expanded);
	}

	bool GetFoldExpanded(int line) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETFOLDEXPANDED, (WPARAM) line, 0);
	}

	void ToggleFold(int line) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_TOGGLEFOLD, (WPARAM) line, 0);
	}

	void FoldLine(int line, int action) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_FOLDLINE, (WPARAM) line, (LPARAM) action);
	}

	void FoldChildren(int line, int action) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_FOLDCHILDREN, (WPARAM) line, (LPARAM) action);
	}

	void ExpandChildren(int line, int level) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_EXPANDCHILDREN, (WPARAM) line, (LPARAM) level);
	}

	void FoldAll(int action) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_FOLDALL, (WPARAM) action, 0);
	}

	void EnsureVisible(int line) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_ENSUREVISIBLE, (WPARAM) line, 0);
	}

	void SetAutomaticFold(int automaticFold) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETAUTOMATICFOLD, (WPARAM) automaticFold, 0);
	}

	int GetAutomaticFold() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETAUTOMATICFOLD, 0, 0);
	}

	void SetFoldFlags(int flags) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETFOLDFLAGS, (WPARAM) flags, 0);
	}

	void EnsureVisibleEnforcePolicy(int line) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_ENSUREVISIBLEENFORCEPOLICY, (WPARAM) line, 0);
	}

	void SetTabIndents(bool tabIndents) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETTABINDENTS, (WPARAM) tabIndents, 0);
	}

	bool GetTabIndents() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETTABINDENTS, 0, 0);
	}

	void SetBackSpaceUnIndents(bool bsUnIndents) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETBACKSPACEUNINDENTS, (WPARAM) bsUnIndents, 0);
	}

	bool GetBackSpaceUnIndents() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETBACKSPACEUNINDENTS, 0, 0);
	}

	void SetMouseDwellTime(int periodMilliseconds) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETMOUSEDWELLTIME, (WPARAM) periodMilliseconds, 0);
	}

	int GetMouseDwellTime() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETMOUSEDWELLTIME, 0, 0);
	}

	int WordStartPosition(int pos, bool onlyWordCharacters) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_WORDSTARTPOSITION, (WPARAM) pos, (LPARAM) onlyWordCharacters);
	}

	int WordEndPosition(int pos, bool onlyWordCharacters) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_WORDENDPOSITION, (WPARAM) pos, (LPARAM) onlyWordCharacters);
	}

	void SetWrapMode(int mode) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETWRAPMODE, (WPARAM) mode, 0);
	}

	int GetWrapMode() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETWRAPMODE, 0, 0);
	}

	void SetWrapVisualFlags(int wrapVisualFlags) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETWRAPVISUALFLAGS, (WPARAM) wrapVisualFlags, 0);
	}

	int GetWrapVisualFlags() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETWRAPVISUALFLAGS, 0, 0);
	}

	void SetWrapVisualFlagsLocation(int wrapVisualFlagsLocation) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETWRAPVISUALFLAGSLOCATION, (WPARAM) wrapVisualFlagsLocation, 0);
	}

	int GetWrapVisualFlagsLocation() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETWRAPVISUALFLAGSLOCATION, 0, 0);
	}

	void SetWrapStartIndent(int indent) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETWRAPSTARTINDENT, (WPARAM) indent, 0);
	}

	int GetWrapStartIndent() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETWRAPSTARTINDENT, 0, 0);
	}

	void SetWrapIndentMode(int mode) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETWRAPINDENTMODE, (WPARAM) mode, 0);
	}

	int GetWrapIndentMode() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETWRAPINDENTMODE, 0, 0);
	}

	void SetLayoutCache(int mode) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETLAYOUTCACHE, (WPARAM) mode, 0);
	}

	int GetLayoutCache() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETLAYOUTCACHE, 0, 0);
	}

	void SetScrollWidth(int pixelWidth) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETSCROLLWIDTH, (WPARAM) pixelWidth, 0);
	}

	int GetScrollWidth() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETSCROLLWIDTH, 0, 0);
	}

	void SetScrollWidthTracking(bool tracking) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETSCROLLWIDTHTRACKING, (WPARAM) tracking, 0);
	}

	bool GetScrollWidthTracking() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETSCROLLWIDTHTRACKING, 0, 0);
	}

	int TextWidth(int style, LPCSTR text) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_TEXTWIDTH, (WPARAM) style, (LPARAM) text);
	}

	void SetEndAtLastLine(bool endAtLastLine) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETENDATLASTLINE, (WPARAM) endAtLastLine, 0);
	}

	bool GetEndAtLastLine() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETENDATLASTLINE, 0, 0);
	}

	int TextHeight(int line) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_TEXTHEIGHT, (WPARAM) line, 0);
	}

	void SetVScrollBar(bool show) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETVSCROLLBAR, (WPARAM) show, 0);
	}

	bool GetVScrollBar() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETVSCROLLBAR, 0, 0);
	}

	void AppendText(int length, LPCSTR text) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_APPENDTEXT, (WPARAM) length, (LPARAM) text);
	}

	bool GetTwoPhaseDraw() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETTWOPHASEDRAW, 0, 0);
	}

	void SetTwoPhaseDraw(bool twoPhase) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETTWOPHASEDRAW, (WPARAM) twoPhase, 0);
	}

	void SetFontQuality(int fontQuality) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETFONTQUALITY, (WPARAM) fontQuality, 0);
	}

	int GetFontQuality() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETFONTQUALITY, 0, 0);
	}

	void SetFirstVisibleLine(int lineDisplay) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETFIRSTVISIBLELINE, (WPARAM) lineDisplay, 0);
	}

	void SetMultiPaste(int multiPaste) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETMULTIPASTE, (WPARAM) multiPaste, 0);
	}

	int GetMultiPaste() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETMULTIPASTE, 0, 0);
	}

	int GetTag(int tagNumber, LPSTR tagValue) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETTAG, (WPARAM) tagNumber, (LPARAM) tagValue);
	}

	int GetTag(int tagNumber, CSimpleStringA& strText) const
	{
		int nLength;
		LPSTR pszText;

		nLength = GetTagLength(tagNumber);
		pszText = strText.GetBuffer(nLength+1);
		nLength = GetTag(tagNumber, pszText);
		strText.ReleaseBuffer();

		return nLength;
	}

	int GetTagLength(int tagNumber) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETTAG, (WPARAM) tagNumber, 0)
	}

	void TargetFromSelection() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_TARGETFROMSELECTION, 0, 0);
	}

	void LinesJoin() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_LINESJOIN, 0, 0);
	}

	void LinesSplit(int pixelWidth) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_LINESSPLIT, (WPARAM) pixelWidth, 0);
	}

	void SetFoldMarginColour(bool useSetting, COLORREF back) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETFOLDMARGINCOLOUR, (WPARAM) useSetting, (LPARAM) back);
	}

	void SetFoldMarginHiColour(bool useSetting, COLORREF fore) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETFOLDMARGINHICOLOUR, (WPARAM) useSetting, (LPARAM) fore);
	}

	void LineDown() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_LINEDOWN, 0, 0);
	}

	void LineDownExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_LINEDOWNEXTEND, 0, 0);
	}

	void LineUp() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_LINEUP, 0, 0);
	}

	void LineUpExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_LINEUPEXTEND, 0, 0);
	}

	void CharLeft() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_CHARLEFT, 0, 0);
	}

	void CharLeftExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_CHARLEFTEXTEND, 0, 0);
	}

	void CharRight() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_CHARRIGHT, 0, 0);
	}

	void CharRightExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_CHARRIGHTEXTEND, 0, 0);
	}

	void WordLeft() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_WORDLEFT, 0, 0);
	}

	void WordLeftExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_WORDLEFTEXTEND, 0, 0);
	}

	void WordRight() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_WORDRIGHT, 0, 0);
	}

	void WordRightExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_WORDRIGHTEXTEND, 0, 0);
	}

	void Home() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_HOME, 0, 0);
	}

	void HomeExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_HOMEEXTEND, 0, 0);
	}

	void LineEnd() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_LINEEND, 0, 0);
	}

	void LineEndExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_LINEENDEXTEND, 0, 0);
	}

	void DocumentStart() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_DOCUMENTSTART, 0, 0);
	}

	void DocumentStartExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_DOCUMENTSTARTEXTEND, 0, 0);
	}

	void DocumentEnd() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_DOCUMENTEND, 0, 0);
	}

	void DocumentEndExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_DOCUMENTENDEXTEND, 0, 0);
	}

	void PageUp() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_PAGEUP, 0, 0);
	}

	void PageUpExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_PAGEUPEXTEND, 0, 0);
	}

	void PageDown() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_PAGEDOWN, 0, 0);
	}

	void PageDownExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_PAGEDOWNEXTEND, 0, 0);
	}

	void EditToggleOvertype() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_EDITTOGGLEOVERTYPE, 0, 0);
	}

	void Cancel() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_CANCEL, 0, 0);
	}

	void DeleteBack() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_DELETEBACK, 0, 0);
	}

	void Tab() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_TAB, 0, 0);
	}

	void BackTab() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_BACKTAB, 0, 0);
	}

	void NewLine() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_NEWLINE, 0, 0);
	}

	void FormFeed() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_FORMFEED, 0, 0);
	}

	void VCHome() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_VCHOME, 0, 0);
	}

	void VCHomeExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_VCHOMEEXTEND, 0, 0);
	}

	void ZoomIn() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_ZOOMIN, 0, 0);
	}

	void ZoomOut() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_ZOOMOUT, 0, 0);
	}

	void DelWordLeft() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_DELWORDLEFT, 0, 0);
	}

	void DelWordRight() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_DELWORDRIGHT, 0, 0);
	}

	void DelWordRightEnd() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_DELWORDRIGHTEND, 0, 0);
	}

	void LineCut() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_LINECUT, 0, 0);
	}

	void LineDelete() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_LINEDELETE, 0, 0);
	}

	void LineTranspose() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_LINETRANSPOSE, 0, 0);
	}

	void LineDuplicate() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_LINEDUPLICATE, 0, 0);
	}

	void LowerCase() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_LOWERCASE, 0, 0);
	}

	void UpperCase() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_UPPERCASE, 0, 0);
	}

	void LineScrollDown() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_LINESCROLLDOWN, 0, 0);
	}

	void LineScrollUp() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_LINESCROLLUP, 0, 0);
	}

	void DeleteBackNotLine() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_DELETEBACKNOTLINE, 0, 0);
	}

	void HomeDisplay() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_HOMEDISPLAY, 0, 0);
	}

	void HomeDisplayExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_HOMEDISPLAYEXTEND, 0, 0);
	}

	void LineEndDisplay() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_LINEENDDISPLAY, 0, 0);
	}

	void LineEndDisplayExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_LINEENDDISPLAYEXTEND, 0, 0);
	}

	void HomeWrap() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_HOMEWRAP, 0, 0);
	}

	void HomeWrapExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_HOMEWRAPEXTEND, 0, 0);
	}

	void LineEndWrap() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_LINEENDWRAP, 0, 0);
	}

	void LineEndWrapExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_LINEENDWRAPEXTEND, 0, 0);
	}

	void VCHomeWrap() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_VCHOMEWRAP, 0, 0);
	}

	void VCHomeWrapExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_VCHOMEWRAPEXTEND, 0, 0);
	}

	void LineCopy() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_LINECOPY, 0, 0);
	}

	void MoveCaretInsideView() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_MOVECARETINSIDEVIEW, 0, 0);
	}

	int LineLength(int line) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_LINELENGTH, (WPARAM) line, 0);
	}

	void BraceHighlight(int pos1, int pos2) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_BRACEHIGHLIGHT, (WPARAM) pos1, (LPARAM) pos2);
	}

	void BraceHighlightIndicator(bool useBraceHighlightIndicator, int indicator) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_BRACEHIGHLIGHTINDICATOR, (WPARAM) useBraceHighlightIndicator, (LPARAM) indicator);
	}

	void BraceBadLight(int pos) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_BRACEBADLIGHT, (WPARAM) pos, 0);
	}

	void BraceBadLightIndicator(bool useBraceBadLightIndicator, int indicator) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_BRACEBADLIGHTINDICATOR, (WPARAM) useBraceBadLightIndicator, (LPARAM) indicator);
	}

	int BraceMatch(int pos) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_BRACEMATCH, (WPARAM) pos, 0);
	}

	bool GetViewEOL() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETVIEWEOL, 0, 0);
	}

	void SetViewEOL(bool visible) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETVIEWEOL, (WPARAM) visible, 0);
	}

	int GetDocPointer() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETDOCPOINTER, 0, 0);
	}

	void SetDocPointer(int pointer) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETDOCPOINTER, 0, (LPARAM) pointer);
	}

	void SetModEventMask(int mask) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETMODEVENTMASK, (WPARAM) mask, 0);
	}

	int GetEdgeColumn() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETEDGECOLUMN, 0, 0);
	}

	void SetEdgeColumn(int column) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETEDGECOLUMN, (WPARAM) column, 0);
	}

	int GetEdgeMode() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETEDGEMODE, 0, 0);
	}

	void SetEdgeMode(int mode) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETEDGEMODE, (WPARAM) mode, 0);
	}

	COLORREF GetEdgeColour() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETEDGECOLOUR, 0, 0);
	}

	void SetEdgeColour(COLORREF edgeColour) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETEDGECOLOUR, (WPARAM) edgeColour, 0);
	}

	void SearchAnchor() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SEARCHANCHOR, 0, 0);
	}

	int SearchNext(int flags, LPCSTR text) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_SEARCHNEXT, (WPARAM) flags, (LPARAM) text);
	}

	int SearchPrev(int flags, LPCSTR text) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_SEARCHPREV, (WPARAM) flags, (LPARAM) text);
	}

	int LinesOnScreen() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_LINESONSCREEN, 0, 0);
	}

	void UsePopUp(bool allowPopUp) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_USEPOPUP, (WPARAM) allowPopUp, 0);
	}

	bool SelectionIsRectangle() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_SELECTIONISRECTANGLE, 0, 0);
	}

	void SetZoom(int zoom) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETZOOM, (WPARAM) zoom, 0);
	}

	int GetZoom() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETZOOM, 0, 0);
	}

	int CreateDocument() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_CREATEDOCUMENT, 0, 0);
	}

	void AddRefDocument(int doc) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_ADDREFDOCUMENT, 0, (LPARAM) doc);
	}

	void ReleaseDocument(int doc) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_RELEASEDOCUMENT, 0, (LPARAM) doc);
	}

	int GetModEventMask() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETMODEVENTMASK, 0, 0);
	}

	void SetFocus(bool focus) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETFOCUS, (WPARAM) focus, 0);
	}

	bool GetFocus() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETFOCUS, 0, 0);
	}

	void SetStatus(int statusCode) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETSTATUS, (WPARAM) statusCode, 0);
	}

	int GetStatus() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETSTATUS, 0, 0);
	}

	void SetMouseDownCaptures(bool captures) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETMOUSEDOWNCAPTURES, (WPARAM) captures, 0);
	}

	bool GetMouseDownCaptures() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETMOUSEDOWNCAPTURES, 0, 0);
	}

	void SetCursor(int cursorType) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETCURSOR, (WPARAM) cursorType, 0);
	}

	int GetCursor() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETCURSOR, 0, 0);
	}

	void SetControlCharSymbol(int symbol) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETCONTROLCHARSYMBOL, (WPARAM) symbol, 0);
	}

	int GetControlCharSymbol() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETCONTROLCHARSYMBOL, 0, 0);
	}

	void WordPartLeft() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_WORDPARTLEFT, 0, 0);
	}

	void WordPartLeftExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_WORDPARTLEFTEXTEND, 0, 0);
	}

	void WordPartRight() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_WORDPARTRIGHT, 0, 0);
	}

	void WordPartRightExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_WORDPARTRIGHTEXTEND, 0, 0);
	}

	void SetVisiblePolicy(int visiblePolicy, int visibleSlop) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETVISIBLEPOLICY, (WPARAM) visiblePolicy, (LPARAM) visibleSlop);
	}

	void DelLineLeft() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_DELLINELEFT, 0, 0);
	}

	void DelLineRight() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_DELLINERIGHT, 0, 0);
	}

	void SetXOffset(int newOffset) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETXOFFSET, (WPARAM) newOffset, 0);
	}

	int GetXOffset() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETXOFFSET, 0, 0);
	}

	void ChooseCaretX() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_CHOOSECARETX, 0, 0);
	}

	void GrabFocus() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_GRABFOCUS, 0, 0);
	}

	void SetXCaretPolicy(int caretPolicy, int caretSlop) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETXCARETPOLICY, (WPARAM) caretPolicy, (LPARAM) caretSlop);
	}

	void SetYCaretPolicy(int caretPolicy, int caretSlop) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETYCARETPOLICY, (WPARAM) caretPolicy, (LPARAM) caretSlop);
	}

	void SetPrintWrapMode(int mode) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETPRINTWRAPMODE, (WPARAM) mode, 0);
	}

	int GetPrintWrapMode() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETPRINTWRAPMODE, 0, 0);
	}

	void SetHotspotActiveFore(bool useSetting, COLORREF fore) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETHOTSPOTACTIVEFORE, (WPARAM) useSetting, (LPARAM) fore);
	}

	COLORREF GetHotspotActiveFore() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETHOTSPOTACTIVEFORE, 0, 0);
	}

	void SetHotspotActiveBack(bool useSetting, COLORREF back) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETHOTSPOTACTIVEBACK, (WPARAM) useSetting, (LPARAM) back);
	}

	COLORREF GetHotspotActiveBack() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETHOTSPOTACTIVEBACK, 0, 0);
	}

	void SetHotspotActiveUnderline(bool underline) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETHOTSPOTACTIVEUNDERLINE, (WPARAM) underline, 0);
	}

	bool GetHotspotActiveUnderline() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETHOTSPOTACTIVEUNDERLINE, 0, 0);
	}

	void SetHotspotSingleLine(bool singleLine) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETHOTSPOTSINGLELINE, (WPARAM) singleLine, 0);
	}

	bool GetHotspotSingleLine() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETHOTSPOTSINGLELINE, 0, 0);
	}

	void ParaDown() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_PARADOWN, 0, 0);
	}

	void ParaDownExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_PARADOWNEXTEND, 0, 0);
	}

	void ParaUp() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_PARAUP, 0, 0);
	}

	void ParaUpExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_PARAUPEXTEND, 0, 0);
	}

	int PositionBefore(int pos) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_POSITIONBEFORE, (WPARAM) pos, 0);
	}

	int PositionAfter(int pos) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_POSITIONAFTER, (WPARAM) pos, 0);
	}

	int PositionRelative(int pos, int relative) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_POSITIONRELATIVE, (WPARAM) pos, (LPARAM) relative);
	}

	void CopyRange(int start, int end) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_COPYRANGE, (WPARAM) start, (LPARAM) end);
	}

	void CopyText(int length, LPCSTR text) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_COPYTEXT, (WPARAM) length, (LPARAM) text);
	}

	void SetSelectionMode(int mode) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETSELECTIONMODE, (WPARAM) mode, 0);
	}

	int GetSelectionMode() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETSELECTIONMODE, 0, 0);
	}

	int GetLineSelStartPosition(int line) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETLINESELSTARTPOSITION, (WPARAM) line, 0);
	}

	int GetLineSelEndPosition(int line) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETLINESELENDPOSITION, (WPARAM) line, 0);
	}

	void LineDownRectExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_LINEDOWNRECTEXTEND, 0, 0);
	}

	void LineUpRectExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_LINEUPRECTEXTEND, 0, 0);
	}

	void CharLeftRectExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_CHARLEFTRECTEXTEND, 0, 0);
	}

	void CharRightRectExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_CHARRIGHTRECTEXTEND, 0, 0);
	}

	void HomeRectExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_HOMERECTEXTEND, 0, 0);
	}

	void VCHomeRectExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_VCHOMERECTEXTEND, 0, 0);
	}

	void LineEndRectExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_LINEENDRECTEXTEND, 0, 0);
	}

	void PageUpRectExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_PAGEUPRECTEXTEND, 0, 0);
	}

	void PageDownRectExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_PAGEDOWNRECTEXTEND, 0, 0);
	}

	void StutteredPageUp() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_STUTTEREDPAGEUP, 0, 0);
	}

	void StutteredPageUpExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_STUTTEREDPAGEUPEXTEND, 0, 0);
	}

	void StutteredPageDown() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_STUTTEREDPAGEDOWN, 0, 0);
	}

	void StutteredPageDownExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_STUTTEREDPAGEDOWNEXTEND, 0, 0);
	}

	void WordLeftEnd() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_WORDLEFTEND, 0, 0);
	}

	void WordLeftEndExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_WORDLEFTENDEXTEND, 0, 0);
	}

	void WordRightEnd() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_WORDRIGHTEND, 0, 0);
	}

	void WordRightEndExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_WORDRIGHTENDEXTEND, 0, 0);
	}

	void SetWhitespaceChars(LPCSTR characters) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETWHITESPACECHARS, 0, (LPARAM) characters);
	}

	int GetWhitespaceChars(LPSTR characters) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETWHITESPACECHARS, 0, (LPARAM) characters);
	}

	int GetWhitespaceChars(CSimpleStringA& strText) const
	{
		int nLength;
		LPSTR pszText;

		nLength = GetWhitespaceCharsLength();
		pszText = strText.GetBuffer(nLength+1);
		nLength = GetWhitespaceChars(pszText);
		strText.ReleaseBuffer();

		return nLength;
	}

	int GetWhitespaceCharsLength() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETWHITESPACECHARS, 0)
	}

	void SetPunctuationChars(LPCSTR characters) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETPUNCTUATIONCHARS, 0, (LPARAM) characters);
	}

	int GetPunctuationChars(LPSTR characters) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETPUNCTUATIONCHARS, 0, (LPARAM) characters);
	}

	int GetPunctuationChars(CSimpleStringA& strText) const
	{
		int nLength;
		LPSTR pszText;

		nLength = GetPunctuationCharsLength();
		pszText = strText.GetBuffer(nLength+1);
		nLength = GetPunctuationChars(pszText);
		strText.ReleaseBuffer();

		return nLength;
	}

	int GetPunctuationCharsLength() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETPUNCTUATIONCHARS, 0)
	}

	void SetCharsDefault() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETCHARSDEFAULT, 0, 0);
	}

	int AutoCGetCurrent() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_AUTOCGETCURRENT, 0, 0);
	}

	int AutoCGetCurrentText(LPSTR s) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_AUTOCGETCURRENTTEXT, 0, (LPARAM) s);
	}

	int AutoCGetCurrentText(CSimpleStringA& strText) const
	{
		int nLength;
		LPSTR pszText;

		nLength = AutoCGetCurrentTextLength();
		pszText = strText.GetBuffer(nLength+1);
		nLength = AutoCGetCurrentText(pszText);
		strText.ReleaseBuffer();

		return nLength;
	}

	int AutoCGetCurrentTextLength() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_AUTOCGETCURRENTTEXT, 0)
	}

	void AutoCSetCaseInsensitiveBehaviour(int behaviour) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_AUTOCSETCASEINSENSITIVEBEHAVIOUR, (WPARAM) behaviour, 0);
	}

	int AutoCGetCaseInsensitiveBehaviour() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_AUTOCGETCASEINSENSITIVEBEHAVIOUR, 0, 0);
	}

	void AutoCSetMulti(int multi) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_AUTOCSETMULTI, (WPARAM) multi, 0);
	}

	int AutoCGetMulti() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_AUTOCGETMULTI, 0, 0);
	}

	void AutoCSetOrder(int order) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_AUTOCSETORDER, (WPARAM) order, 0);
	}

	int AutoCGetOrder() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_AUTOCGETORDER, 0, 0);
	}

	void Allocate(int bytes) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_ALLOCATE, (WPARAM) bytes, 0);
	}

	int TargetAsUTF8(LPSTR s) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_TARGETASUTF8, 0, (LPARAM) s);
	}

	int TargetAsUTF8(CSimpleStringA& strText) const
	{
		int nLength;
		LPSTR pszText;

		nLength = TargetAsUTF8Length();
		pszText = strText.GetBuffer(nLength+1);
		nLength = TargetAsUTF8(pszText);
		strText.ReleaseBuffer();

		return nLength;
	}

	int TargetAsUTF8Length() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_TARGETASUTF8, 0)
	}

	void SetLengthForEncode(int bytes) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETLENGTHFORENCODE, (WPARAM) bytes, 0);
	}

	int EncodedFromUTF8(LPCSTR utf8, LPSTR encoded) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_ENCODEDFROMUTF8, (WPARAM) utf8, (LPARAM) encoded);
	}

	int EncodedFromUTF8(LPCSTR utf8, CSimpleStringA& strText) const
	{
		int nLength;
		LPSTR pszText;

		nLength = EncodedFromUTF8Length(utf8);
		pszText = strText.GetBuffer(nLength+1);
		nLength = EncodedFromUTF8(utf8, pszText);
		strText.ReleaseBuffer();

		return nLength;
	}

	int EncodedFromUTF8Length(LPCSTR utf8) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_ENCODEDFROMUTF8, (WPARAM) utf8, 0)
	}

	int FindColumn(int line, int column) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_FINDCOLUMN, (WPARAM) line, (LPARAM) column);
	}

	int GetCaretSticky() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETCARETSTICKY, 0, 0);
	}

	void SetCaretSticky(int useCaretStickyBehaviour) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETCARETSTICKY, (WPARAM) useCaretStickyBehaviour, 0);
	}

	void ToggleCaretSticky() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_TOGGLECARETSTICKY, 0, 0);
	}

	void SetPasteConvertEndings(bool convert) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETPASTECONVERTENDINGS, (WPARAM) convert, 0);
	}

	bool GetPasteConvertEndings() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETPASTECONVERTENDINGS, 0, 0);
	}

	void SelectionDuplicate() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SELECTIONDUPLICATE, 0, 0);
	}

	void SetCaretLineBackAlpha(int alpha) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETCARETLINEBACKALPHA, (WPARAM) alpha, 0);
	}

	int GetCaretLineBackAlpha() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETCARETLINEBACKALPHA, 0, 0);
	}

	void SetCaretStyle(int caretStyle) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETCARETSTYLE, (WPARAM) caretStyle, 0);
	}

	int GetCaretStyle() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETCARETSTYLE, 0, 0);
	}

	void SetIndicatorCurrent(int indicator) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETINDICATORCURRENT, (WPARAM) indicator, 0);
	}

	int GetIndicatorCurrent() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETINDICATORCURRENT, 0, 0);
	}

	void SetIndicatorValue(int value) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETINDICATORVALUE, (WPARAM) value, 0);
	}

	int GetIndicatorValue() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETINDICATORVALUE, 0, 0);
	}

	void IndicatorFillRange(int position, int fillLength) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_INDICATORFILLRANGE, (WPARAM) position, (LPARAM) fillLength);
	}

	void IndicatorClearRange(int position, int clearLength) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_INDICATORCLEARRANGE, (WPARAM) position, (LPARAM) clearLength);
	}

	int IndicatorAllOnFor(int position) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_INDICATORALLONFOR, (WPARAM) position, 0);
	}

	int IndicatorValueAt(int indicator, int position) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_INDICATORVALUEAT, (WPARAM) indicator, (LPARAM) position);
	}

	int IndicatorStart(int indicator, int position) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_INDICATORSTART, (WPARAM) indicator, (LPARAM) position);
	}

	int IndicatorEnd(int indicator, int position) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_INDICATOREND, (WPARAM) indicator, (LPARAM) position);
	}

	void SetPositionCache(int size) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETPOSITIONCACHE, (WPARAM) size, 0);
	}

	int GetPositionCache() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETPOSITIONCACHE, 0, 0);
	}

	void CopyAllowLine() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_COPYALLOWLINE, 0, 0);
	}

	int GetCharacterPointer() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETCHARACTERPOINTER, 0, 0);
	}

	int GetRangePointer(int position, int rangeLength) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETRANGEPOINTER, (WPARAM) position, (LPARAM) rangeLength);
	}

	int GetGapPosition() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETGAPPOSITION, 0, 0);
	}

	void SetKeysUnicode(bool keysUnicode) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETKEYSUNICODE, (WPARAM) keysUnicode, 0);
	}

	bool GetKeysUnicode() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETKEYSUNICODE, 0, 0);
	}

	void IndicSetAlpha(int indicator, int alpha) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_INDICSETALPHA, (WPARAM) indicator, (LPARAM) alpha);
	}

	int IndicGetAlpha(int indicator) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_INDICGETALPHA, (WPARAM) indicator, 0);
	}

	void IndicSetOutlineAlpha(int indicator, int alpha) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_INDICSETOUTLINEALPHA, (WPARAM) indicator, (LPARAM) alpha);
	}

	int IndicGetOutlineAlpha(int indicator) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_INDICGETOUTLINEALPHA, (WPARAM) indicator, 0);
	}

	void SetExtraAscent(int extraAscent) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETEXTRAASCENT, (WPARAM) extraAscent, 0);
	}

	int GetExtraAscent() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETEXTRAASCENT, 0, 0);
	}

	void SetExtraDescent(int extraDescent) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETEXTRADESCENT, (WPARAM) extraDescent, 0);
	}

	int GetExtraDescent() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETEXTRADESCENT, 0, 0);
	}

	int MarkerSymbolDefined(int markerNumber) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_MARKERSYMBOLDEFINED, (WPARAM) markerNumber, 0);
	}

	void MarginSetText(int line, LPCSTR text) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_MARGINSETTEXT, (WPARAM) line, (LPARAM) text);
	}

	int MarginGetText(int line, LPSTR text) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_MARGINGETTEXT, (WPARAM) line, (LPARAM) text);
	}

	int MarginGetText(int line, CSimpleStringA& strText) const
	{
		int nLength;
		LPSTR pszText;

		nLength = MarginGetTextLength(line);
		pszText = strText.GetBuffer(nLength+1);
		nLength = MarginGetText(line, pszText);
		strText.ReleaseBuffer();

		return nLength;
	}

	int MarginGetTextLength(int line) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_MARGINGETTEXT, (WPARAM) line, 0)
	}

	void MarginSetStyle(int line, int style) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_MARGINSETSTYLE, (WPARAM) line, (LPARAM) style);
	}

	int MarginGetStyle(int line) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_MARGINGETSTYLE, (WPARAM) line, 0);
	}

	void MarginSetStyles(int line, LPCSTR styles) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_MARGINSETSTYLES, (WPARAM) line, (LPARAM) styles);
	}

	int MarginGetStyles(int line, LPSTR styles) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_MARGINGETSTYLES, (WPARAM) line, (LPARAM) styles);
	}

	int MarginGetStyles(int line, CSimpleStringA& strText) const
	{
		int nLength;
		LPSTR pszText;

		nLength = MarginGetStylesLength(line);
		pszText = strText.GetBuffer(nLength+1);
		nLength = MarginGetStyles(line, pszText);
		strText.ReleaseBuffer();

		return nLength;
	}

	int MarginGetStylesLength(int line) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_MARGINGETSTYLES, (WPARAM) line, 0)
	}

	void MarginTextClearAll() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_MARGINTEXTCLEARALL, 0, 0);
	}

	void MarginSetStyleOffset(int style) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_MARGINSETSTYLEOFFSET, (WPARAM) style, 0);
	}

	int MarginGetStyleOffset() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_MARGINGETSTYLEOFFSET, 0, 0);
	}

	void SetMarginOptions(int marginOptions) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETMARGINOPTIONS, (WPARAM) marginOptions, 0);
	}

	int GetMarginOptions() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETMARGINOPTIONS, 0, 0);
	}

	void AnnotationSetText(int line, LPCSTR text) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_ANNOTATIONSETTEXT, (WPARAM) line, (LPARAM) text);
	}

	int AnnotationGetText(int line, LPSTR text) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_ANNOTATIONGETTEXT, (WPARAM) line, (LPARAM) text);
	}

	int AnnotationGetText(int line, CSimpleStringA& strText) const
	{
		int nLength;
		LPSTR pszText;

		nLength = AnnotationGetTextLength(line);
		pszText = strText.GetBuffer(nLength+1);
		nLength = AnnotationGetText(line, pszText);
		strText.ReleaseBuffer();

		return nLength;
	}

	int AnnotationGetTextLength(int line) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_ANNOTATIONGETTEXT, (WPARAM) line, 0)
	}

	void AnnotationSetStyle(int line, int style) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_ANNOTATIONSETSTYLE, (WPARAM) line, (LPARAM) style);
	}

	int AnnotationGetStyle(int line) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_ANNOTATIONGETSTYLE, (WPARAM) line, 0);
	}

	void AnnotationSetStyles(int line, LPCSTR styles) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_ANNOTATIONSETSTYLES, (WPARAM) line, (LPARAM) styles);
	}

	int AnnotationGetStyles(int line, LPSTR styles) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_ANNOTATIONGETSTYLES, (WPARAM) line, (LPARAM) styles);
	}

	int AnnotationGetStyles(int line, CSimpleStringA& strText) const
	{
		int nLength;
		LPSTR pszText;

		nLength = AnnotationGetStylesLength(line);
		pszText = strText.GetBuffer(nLength+1);
		nLength = AnnotationGetStyles(line, pszText);
		strText.ReleaseBuffer();

		return nLength;
	}

	int AnnotationGetStylesLength(int line) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_ANNOTATIONGETSTYLES, (WPARAM) line, 0)
	}

	int AnnotationGetLines(int line) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_ANNOTATIONGETLINES, (WPARAM) line, 0);
	}

	void AnnotationClearAll() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_ANNOTATIONCLEARALL, 0, 0);
	}

	void AnnotationSetVisible(int visible) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_ANNOTATIONSETVISIBLE, (WPARAM) visible, 0);
	}

	int AnnotationGetVisible() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_ANNOTATIONGETVISIBLE, 0, 0);
	}

	void AnnotationSetStyleOffset(int style) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_ANNOTATIONSETSTYLEOFFSET, (WPARAM) style, 0);
	}

	int AnnotationGetStyleOffset() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_ANNOTATIONGETSTYLEOFFSET, 0, 0);
	}

	void ReleaseAllExtendedStyles() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_RELEASEALLEXTENDEDSTYLES, 0, 0);
	}

	int AllocateExtendedStyles(int numberStyles) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_ALLOCATEEXTENDEDSTYLES, (WPARAM) numberStyles, 0);
	}

	void AddUndoAction(int token, int flags) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_ADDUNDOACTION, (WPARAM) token, (LPARAM) flags);
	}

	int CharPositionFromPoint(int x, int y) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_CHARPOSITIONFROMPOINT, (WPARAM) x, (LPARAM) y);
	}

	int CharPositionFromPointClose(int x, int y) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_CHARPOSITIONFROMPOINTCLOSE, (WPARAM) x, (LPARAM) y);
	}

	void SetMouseSelectionRectangularSwitch(bool mouseSelectionRectangularSwitch) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETMOUSESELECTIONRECTANGULARSWITCH, (WPARAM) mouseSelectionRectangularSwitch, 0);
	}

	bool GetMouseSelectionRectangularSwitch() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETMOUSESELECTIONRECTANGULARSWITCH, 0, 0);
	}

	void SetMultipleSelection(bool multipleSelection) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETMULTIPLESELECTION, (WPARAM) multipleSelection, 0);
	}

	bool GetMultipleSelection() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETMULTIPLESELECTION, 0, 0);
	}

	void SetAdditionalSelectionTyping(bool additionalSelectionTyping) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETADDITIONALSELECTIONTYPING, (WPARAM) additionalSelectionTyping, 0);
	}

	bool GetAdditionalSelectionTyping() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETADDITIONALSELECTIONTYPING, 0, 0);
	}

	void SetAdditionalCaretsBlink(bool additionalCaretsBlink) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETADDITIONALCARETSBLINK, (WPARAM) additionalCaretsBlink, 0);
	}

	bool GetAdditionalCaretsBlink() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETADDITIONALCARETSBLINK, 0, 0);
	}

	void SetAdditionalCaretsVisible(bool additionalCaretsBlink) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETADDITIONALCARETSVISIBLE, (WPARAM) additionalCaretsBlink, 0);
	}

	bool GetAdditionalCaretsVisible() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETADDITIONALCARETSVISIBLE, 0, 0);
	}

	int GetSelections() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETSELECTIONS, 0, 0);
	}

	bool GetSelectionEmpty() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETSELECTIONEMPTY, 0, 0);
	}

	void ClearSelections() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_CLEARSELECTIONS, 0, 0);
	}

	int SetSelection(int caret, int anchor) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_SETSELECTION, (WPARAM) caret, (LPARAM) anchor);
	}

	int AddSelection(int caret, int anchor) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_ADDSELECTION, (WPARAM) caret, (LPARAM) anchor);
	}

	void DropSelectionN(int selection) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_DROPSELECTIONN, (WPARAM) selection, 0);
	}

	void SetMainSelection(int selection) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETMAINSELECTION, (WPARAM) selection, 0);
	}

	int GetMainSelection() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETMAINSELECTION, 0, 0);
	}

	void SetSelectionNCaret(int selection, int pos) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETSELECTIONNCARET, (WPARAM) selection, (LPARAM) pos);
	}

	int GetSelectionNCaret(int selection) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETSELECTIONNCARET, (WPARAM) selection, 0);
	}

	void SetSelectionNAnchor(int selection, int posAnchor) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETSELECTIONNANCHOR, (WPARAM) selection, (LPARAM) posAnchor);
	}

	int GetSelectionNAnchor(int selection) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETSELECTIONNANCHOR, (WPARAM) selection, 0);
	}

	void SetSelectionNCaretVirtualSpace(int selection, int space) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETSELECTIONNCARETVIRTUALSPACE, (WPARAM) selection, (LPARAM) space);
	}

	int GetSelectionNCaretVirtualSpace(int selection) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETSELECTIONNCARETVIRTUALSPACE, (WPARAM) selection, 0);
	}

	void SetSelectionNAnchorVirtualSpace(int selection, int space) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETSELECTIONNANCHORVIRTUALSPACE, (WPARAM) selection, (LPARAM) space);
	}

	int GetSelectionNAnchorVirtualSpace(int selection) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETSELECTIONNANCHORVIRTUALSPACE, (WPARAM) selection, 0);
	}

	void SetSelectionNStart(int selection, int pos) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETSELECTIONNSTART, (WPARAM) selection, (LPARAM) pos);
	}

	int GetSelectionNStart(int selection) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETSELECTIONNSTART, (WPARAM) selection, 0);
	}

	void SetSelectionNEnd(int selection, int pos) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETSELECTIONNEND, (WPARAM) selection, (LPARAM) pos);
	}

	int GetSelectionNEnd(int selection) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETSELECTIONNEND, (WPARAM) selection, 0);
	}

	void SetRectangularSelectionCaret(int pos) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETRECTANGULARSELECTIONCARET, (WPARAM) pos, 0);
	}

	int GetRectangularSelectionCaret() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETRECTANGULARSELECTIONCARET, 0, 0);
	}

	void SetRectangularSelectionAnchor(int posAnchor) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETRECTANGULARSELECTIONANCHOR, (WPARAM) posAnchor, 0);
	}

	int GetRectangularSelectionAnchor() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETRECTANGULARSELECTIONANCHOR, 0, 0);
	}

	void SetRectangularSelectionCaretVirtualSpace(int space) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETRECTANGULARSELECTIONCARETVIRTUALSPACE, (WPARAM) space, 0);
	}

	int GetRectangularSelectionCaretVirtualSpace() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETRECTANGULARSELECTIONCARETVIRTUALSPACE, 0, 0);
	}

	void SetRectangularSelectionAnchorVirtualSpace(int space) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETRECTANGULARSELECTIONANCHORVIRTUALSPACE, (WPARAM) space, 0);
	}

	int GetRectangularSelectionAnchorVirtualSpace() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETRECTANGULARSELECTIONANCHORVIRTUALSPACE, 0, 0);
	}

	void SetVirtualSpaceOptions(int virtualSpaceOptions) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETVIRTUALSPACEOPTIONS, (WPARAM) virtualSpaceOptions, 0);
	}

	int GetVirtualSpaceOptions() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETVIRTUALSPACEOPTIONS, 0, 0);
	}

	void SetRectangularSelectionModifier(int modifier) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETRECTANGULARSELECTIONMODIFIER, (WPARAM) modifier, 0);
	}

	int GetRectangularSelectionModifier() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETRECTANGULARSELECTIONMODIFIER, 0, 0);
	}

	void SetAdditionalSelFore(COLORREF fore) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETADDITIONALSELFORE, (WPARAM) fore, 0);
	}

	void SetAdditionalSelBack(COLORREF back) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETADDITIONALSELBACK, (WPARAM) back, 0);
	}

	void SetAdditionalSelAlpha(int alpha) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETADDITIONALSELALPHA, (WPARAM) alpha, 0);
	}

	int GetAdditionalSelAlpha() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETADDITIONALSELALPHA, 0, 0);
	}

	void SetAdditionalCaretFore(COLORREF fore) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETADDITIONALCARETFORE, (WPARAM) fore, 0);
	}

	COLORREF GetAdditionalCaretFore() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETADDITIONALCARETFORE, 0, 0);
	}

	void RotateSelection() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_ROTATESELECTION, 0, 0);
	}

	void SwapMainAnchorCaret() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SWAPMAINANCHORCARET, 0, 0);
	}

	int ChangeLexerState(int start, int end) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_CHANGELEXERSTATE, (WPARAM) start, (LPARAM) end);
	}

	int ContractedFoldNext(int lineStart) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_CONTRACTEDFOLDNEXT, (WPARAM) lineStart, 0);
	}

	void VerticalCentreCaret() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_VERTICALCENTRECARET, 0, 0);
	}

	void MoveSelectedLinesUp() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_MOVESELECTEDLINESUP, 0, 0);
	}

	void MoveSelectedLinesDown() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_MOVESELECTEDLINESDOWN, 0, 0);
	}

	void SetIdentifier(int identifier) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETIDENTIFIER, (WPARAM) identifier, 0);
	}

	int GetIdentifier() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETIDENTIFIER, 0, 0);
	}

	void RGBAImageSetWidth(int width) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_RGBAIMAGESETWIDTH, (WPARAM) width, 0);
	}

	void RGBAImageSetHeight(int height) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_RGBAIMAGESETHEIGHT, (WPARAM) height, 0);
	}

	void RGBAImageSetScale(int scalePercent) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_RGBAIMAGESETSCALE, (WPARAM) scalePercent, 0);
	}

	void MarkerDefineRGBAImage(int markerNumber, LPCSTR pixels) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_MARKERDEFINERGBAIMAGE, (WPARAM) markerNumber, (LPARAM) pixels);
	}

	void RegisterRGBAImage(int type, LPCSTR pixels) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_REGISTERRGBAIMAGE, (WPARAM) type, (LPARAM) pixels);
	}

	void ScrollToStart() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SCROLLTOSTART, 0, 0);
	}

	void ScrollToEnd() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SCROLLTOEND, 0, 0);
	}

	void SetTechnology(int technology) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETTECHNOLOGY, (WPARAM) technology, 0);
	}

	int GetTechnology() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETTECHNOLOGY, 0, 0);
	}

	int CreateLoader(int bytes) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_CREATELOADER, (WPARAM) bytes, 0);
	}

	void FindIndicatorShow(int start, int end) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_FINDINDICATORSHOW, (WPARAM) start, (LPARAM) end);
	}

	void FindIndicatorFlash(int start, int end) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_FINDINDICATORFLASH, (WPARAM) start, (LPARAM) end);
	}

	void FindIndicatorHide() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_FINDINDICATORHIDE, 0, 0);
	}

	void VCHomeDisplay() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_VCHOMEDISPLAY, 0, 0);
	}

	void VCHomeDisplayExtend() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_VCHOMEDISPLAYEXTEND, 0, 0);
	}

	bool GetCaretLineVisibleAlways() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETCARETLINEVISIBLEALWAYS, 0, 0);
	}

	void SetCaretLineVisibleAlways(bool alwaysVisible) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETCARETLINEVISIBLEALWAYS, (WPARAM) alwaysVisible, 0);
	}

	void SetLineEndTypesAllowed(int lineEndBitSet) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETLINEENDTYPESALLOWED, (WPARAM) lineEndBitSet, 0);
	}

	int GetLineEndTypesAllowed() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETLINEENDTYPESALLOWED, 0, 0);
	}

	int GetLineEndTypesActive() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETLINEENDTYPESACTIVE, 0, 0);
	}

	void SetRepresentation(LPCSTR encodedCharacter, LPCSTR representation) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETREPRESENTATION, (WPARAM) encodedCharacter, (LPARAM) representation);
	}

	int GetRepresentation(LPCSTR encodedCharacter, LPSTR representation) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETREPRESENTATION, (WPARAM) encodedCharacter, (LPARAM) representation);
	}

	int GetRepresentation(LPCSTR encodedCharacter, CSimpleStringA& strText) const
	{
		int nLength;
		LPSTR pszText;

		nLength = GetRepresentationLength(encodedCharacter);
		pszText = strText.GetBuffer(nLength+1);
		nLength = GetRepresentation(encodedCharacter, pszText);
		strText.ReleaseBuffer();

		return nLength;
	}

	int GetRepresentationLength(LPCSTR encodedCharacter) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETREPRESENTATION, (WPARAM) encodedCharacter, 0)
	}

	void ClearRepresentation(LPCSTR encodedCharacter) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_CLEARREPRESENTATION, (WPARAM) encodedCharacter, 0);
	}

	void StartRecord() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_STARTRECORD, 0, 0);
	}

	void StopRecord() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_STOPRECORD, 0, 0);
	}

	void SetLexer(int lexer) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETLEXER, (WPARAM) lexer, 0);
	}

	int GetLexer() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETLEXER, 0, 0);
	}

	void Colourise(int start, int end) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_COLOURISE, (WPARAM) start, (LPARAM) end);
	}

	void SetProperty(LPCSTR key, LPCSTR value) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETPROPERTY, (WPARAM) key, (LPARAM) value);
	}

	void SetKeyWords(int keywordSet, LPCSTR keyWords) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETKEYWORDS, (WPARAM) keywordSet, (LPARAM) keyWords);
	}

	void SetLexerLanguage(LPCSTR language) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETLEXERLANGUAGE, 0, (LPARAM) language);
	}

	void LoadLexerLibrary(LPCSTR path) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_LOADLEXERLIBRARY, 0, (LPARAM) path);
	}

	int GetProperty(LPCSTR key, LPSTR buf) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETPROPERTY, (WPARAM) key, (LPARAM) buf);
	}

	int GetProperty(LPCSTR key, CSimpleStringA& strText) const
	{
		int nLength;
		LPSTR pszText;

		nLength = GetPropertyLength(key);
		pszText = strText.GetBuffer(nLength+1);
		nLength = GetProperty(key, pszText);
		strText.ReleaseBuffer();

		return nLength;
	}

	int GetPropertyLength(LPCSTR key) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETPROPERTY, (WPARAM) key, 0)
	}

	int GetPropertyExpanded(LPCSTR key, LPSTR buf) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETPROPERTYEXPANDED, (WPARAM) key, (LPARAM) buf);
	}

	int GetPropertyExpanded(LPCSTR key, CSimpleStringA& strText) const
	{
		int nLength;
		LPSTR pszText;

		nLength = GetPropertyExpandedLength(key);
		pszText = strText.GetBuffer(nLength+1);
		nLength = GetPropertyExpanded(key, pszText);
		strText.ReleaseBuffer();

		return nLength;
	}

	int GetPropertyExpandedLength(LPCSTR key) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETPROPERTYEXPANDED, (WPARAM) key, 0)
	}

	int GetPropertyInt(LPCSTR key) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETPROPERTYINT, (WPARAM) key, 0);
	}

	int GetStyleBitsNeeded() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETSTYLEBITSNEEDED, 0, 0);
	}

	int GetLexerLanguage(LPSTR text) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETLEXERLANGUAGE, 0, (LPARAM) text);
	}

	int GetLexerLanguage(CSimpleStringA& strText) const
	{
		int nLength;
		LPSTR pszText;

		nLength = GetLexerLanguageLength();
		pszText = strText.GetBuffer(nLength+1);
		nLength = GetLexerLanguage(pszText);
		strText.ReleaseBuffer();

		return nLength;
	}

	int GetLexerLanguageLength() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETLEXERLANGUAGE, 0)
	}

	int PrivateLexerCall(int operation, int pointer) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_PRIVATELEXERCALL, (WPARAM) operation, (LPARAM) pointer);
	}

	int PropertyNames(LPSTR names) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_PROPERTYNAMES, 0, (LPARAM) names);
	}

	int PropertyNames(CSimpleStringA& strText) const
	{
		int nLength;
		LPSTR pszText;

		nLength = PropertyNamesLength();
		pszText = strText.GetBuffer(nLength+1);
		nLength = PropertyNames(pszText);
		strText.ReleaseBuffer();

		return nLength;
	}

	int PropertyNamesLength() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_PROPERTYNAMES, 0)
	}

	int PropertyType(LPCSTR name) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_PROPERTYTYPE, (WPARAM) name, 0);
	}

	int DescribeProperty(LPCSTR name, LPSTR description) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_DESCRIBEPROPERTY, (WPARAM) name, (LPARAM) description);
	}

	int DescribeProperty(LPCSTR name, CSimpleStringA& strText) const
	{
		int nLength;
		LPSTR pszText;

		nLength = DescribePropertyLength(name);
		pszText = strText.GetBuffer(nLength+1);
		nLength = DescribeProperty(name, pszText);
		strText.ReleaseBuffer();

		return nLength;
	}

	int DescribePropertyLength(LPCSTR name) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_DESCRIBEPROPERTY, (WPARAM) name, 0)
	}

	int DescribeKeyWordSets(LPSTR descriptions) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_DESCRIBEKEYWORDSETS, 0, (LPARAM) descriptions);
	}

	int DescribeKeyWordSets(CSimpleStringA& strText) const
	{
		int nLength;
		LPSTR pszText;

		nLength = DescribeKeyWordSetsLength();
		pszText = strText.GetBuffer(nLength+1);
		nLength = DescribeKeyWordSets(pszText);
		strText.ReleaseBuffer();

		return nLength;
	}

	int DescribeKeyWordSetsLength() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_DESCRIBEKEYWORDSETS, 0)
	}

	int GetLineEndTypesSupported() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETLINEENDTYPESSUPPORTED, 0, 0);
	}

	int AllocateSubStyles(int styleBase, int numberStyles) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_ALLOCATESUBSTYLES, (WPARAM) styleBase, (LPARAM) numberStyles);
	}

	int GetSubStylesStart(int styleBase) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETSUBSTYLESSTART, (WPARAM) styleBase, 0);
	}

	int GetSubStylesLength(int styleBase) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETSUBSTYLESLENGTH, (WPARAM) styleBase, 0);
	}

	int GetStyleFromSubStyle(int subStyle) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETSTYLEFROMSUBSTYLE, (WPARAM) subStyle, 0);
	}

	int GetPrimaryStyleFromStyle(int style) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETPRIMARYSTYLEFROMSTYLE, (WPARAM) style, 0);
	}

	void FreeSubStyles() throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_FREESUBSTYLES, 0, 0);
	}

	void SetIdentifiers(int style, LPCSTR identifiers) throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		Call(SCI_SETIDENTIFIERS, (WPARAM) style, (LPARAM) identifiers);
	}

	int DistanceToSecondaryStyles() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_DISTANCETOSECONDARYSTYLES, 0, 0);
	}

	int GetSubStyleBases(LPSTR styles) const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETSUBSTYLEBASES, 0, (LPARAM) styles);
	}

	int GetSubStyleBases(CSimpleStringA& strText) const
	{
		int nLength;
		LPSTR pszText;

		nLength = GetSubStyleBasesLength();
		pszText = strText.GetBuffer(nLength+1);
		nLength = GetSubStyleBases(pszText);
		strText.ReleaseBuffer();

		return nLength;
	}

	int GetSubStyleBasesLength() const throw()
	{
		ATLASSERT(::IsWindow(m_hWnd));
		return Call(SCI_GETSUBSTYLEBASES, 0)
	}

/* --Autogenerated -- end of section automatically generated from Scintilla.iface */

};

typedef CSciLexerCtrlT<ATL::CWindow> CSciLexerCtrl;

}; // namespace WTL

#endif // __ATLSCILEXER_H__
